# Runtime secrets for the backend container, generated by Terraform so nothing
# is hardcoded in source or user_data. Referenced directly where the backend
# container is launched (a later user_data step) — intentionally NOT exposed as
# outputs, since outputs would surface these in plaintext plan/state diffs.

# JWT_SECRET — the backend requires a non-empty string (z.string().min(1)).
# 48 alphanumeric chars is ample entropy. special=false avoids shell-quoting
# hazards when this value is passed into `docker run -e`.
resource "random_password" "jwt_secret" {
  length  = 48
  special = false
}

# ENCRYPTION_KEY — the backend's encryption service requires a value that
# base64-decodes to EXACTLY 32 bytes (AES-256-GCM). random_bytes.length is a
# BYTE count, and its .base64 attribute yields the base64 string the app expects.
# Do NOT use random_password here — that would produce 32 base64 CHARACTERS
# (~24 bytes) and the backend would throw "ENCRYPTION_KEY must decode to 32
# bytes" at startup.
resource "random_bytes" "encryption_key" {
  length = 32
}
